### ISSUE TITLE
 expected update to the latest Valhalla version (3.3.0) 

### ISSUE THREAD

**Issue by ImreSamu** [gis-ops/pyvalhalla#25]
Hello,
I was wondering if there is an expected update to the latest Valhalla version (3.3.0) at some point in the future?  :smile: 
Thank you for your time and consideration.
Best regards,
  Imre

* https://github.com/valhalla/valhalla/tree/3.3.0

**Comment by nilsnolde** [comment]
Yeah, will need to do that at some point. It has very low priority for us at the moment. It's a project we want to embed in another project which is currently (and has been for a few months) on hold. I haven't given up on it and I expect it to start again, ideally even finish it for FOSS4G this year, but well, I said that before.. So don't hold your breath for another couple of months :wink: 

Also I really, really wanted to automate the build process in a smarter way, so it's not such a PITA. I figured I'd only update Valhalla 1-2 times a year, based on the release "schedule" we had until recently. But since I stipulate release pretty regularly lately on upstream Valhalla, this is becoming an unacceptable situation for packaging the bindings.

That said, funding always speeds up the process, so if anyone needs this more urgent, contact me.
